#!/bin/bash

DEFAULT_PATH="$HOME/Pictures"

if [ "$#" -gt 0 ]; then
    if [ -e "$1" ]; then
        DEFAULT_PATH="$1"
    else
        echo "Error: $1 is not a valid path." >&2
        exit 1 
    fi
fi

DISPLAY=:0 /usr/bin/feh --bg-fill --randomize "$DEFAULT_PATH"

